TEAM_TO_FLAG_CODE = {
    "Germany": "de",
    "Scotland": "gb-sct",
    "Hungary": "hu",
    "Switzerland": "ch",
    "Spain": "es",
    "Croatia": "hr",
    "Italy": "it",
    "Albania": "al",
    "Slovenia": "si",
    "Denmark": "dk",
    "Serbia": "rs",
    "England": "gb-eng",
    "Poland": "pl",
    "Netherlands": "nl",
    "Austria": "at",
    "France": "fr",
    "Belgium": "be",
    "Slovakia": "sk",
    "Romania": "ro",
    "Ukraine": "ua",
    "Turkey": "tr",
    "Georgia": "ge",
    "Portugal": "pt",
    "Czech Republic": "cz"
}
