# === File: download_and_flatten_statsbomb_data/remove_any_non_raw_statsbomb_data_if_exists.py ===

"""
Removes intermediate or non-raw data generated by the StatsBomb ETL pipeline.
- Clears all files in: flattened/ and errors/
- Optionally removes the combined event CSV
"""

import os
import shutil

from src.config.constants import FLATTENED_DIR


def remove_contents(folder: str):
    if not os.path.exists(folder):
        print(f"Skipped: {folder} does not exist.")
        return

    files = os.listdir(folder)
    if not files:
        print(f"No files to remove in: {folder}")
        return

    for filename in files:
        file_path = os.path.join(folder, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f"Error removing {file_path}: {e}")
    print(f"Removed all contents from: {folder}")


def run(remove_combined_csv: bool = False):
    """Cleans up non-raw ETL directories. Optionally removes the combined CSV."""
    remove_contents(FLATTENED_DIR)
